kafka:
  image: "cantireinnovations/kafka:0.9.0.0"
  ports:
    - "9092:9092"
  links: 
    - "zookeeper:zookeeper"
  environment:
    KAFKA_BROKER_ID: "1"
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  volumes:
    - "./data/logs:/data/logs"

zookeeper:
  image: "wurstmeister/zookeeper"
  ports:
    - "2181:2181"

