zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"

kafka1:
  image: cantireinnovations/centos-kafka
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.1.237
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_BROKER_ID: 1
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

kafka2:
  image: cantireinnovations/centos-kafka
  ports:
    - "9093:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.1.237
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_BROKER_ID: 2
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

kafka3:
  image: cantireinnovations/centos-kafka
  ports:
    - "9094:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.1.237
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_BROKER_ID: 3
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
