#!/bin/bash
set -e

if [ -z "$CONSUMER_ZOOKEEPER_CONNECT" ]; then
    echo "CONSUMER_ZOOKEEPER_CONNECT not set"
    return 100
fi

if [ -z "$CONSUMER_GROUP" ]; then
    echo "CONSUMER_GROUP not set"
    return 101
fi

if [ -z "$PRODUCER_BROKERS" ]; then
    echo "PRODUCER_BROKERS not set"
    return 200
fi

if [ -z "$TOPICS_WHITELIST" ]; then
    echo "TOPICS_WHITELIST not set"
    return 300
fi

if [ -z "$NUM_STREAMS" ]; then
    NUM_STREAMS=2
fi

mkdir /etc/kafka

# ---------------------------------------------------

CONSUMER_CONFIG=/etc/kafka/consumer.cfg
echo "Generated by start-kafka-mirror-maker" > $CONSUMER_CONFIG
echo "group.id=$CONSUMER_GROUP" >> $CONSUMER_CONFIG
echo "zookeeper.connect=$CONSUMER_ZOOKEEPER_CONNECT" >> $CONSUMER_CONFIG
echo "zookeeper.connection.timeout.ms=6000" >> $CONSUMER_CONFIG

# ---------------------------------------------------

PRODUCER_CONFIG=/etc/kafka/producer.cfg
echo "Generated by start-kafka-mirror-maker" > $PRODUCER_CONFIG
echo "compression.codec=gzip" >> $PRODUCER_CONFIG
echo "metadata.broker.list=$PRODUCER_BROKERS" >> $PRODUCER_CONFIG
echo "producer.type=sync" >> $PRODUCER_CONFIG
echo "serializer.class=kafka.serializer.DefaultEncoder" >> $PRODUCER_CONFIG

# ---------------------------------------------------

$KAFKA_HOME/bin/kafka-run-class.sh kafka.tools.MirrorMaker \
    --consumer.config $CONSUMER_CONFIG \
    --producer.config $PRODUCER_CONFIG \
    --num.streams $NUM_STREAMS \
    --whitelist="$TOPICS_WHITELIST"
